CREATE TABLE ENTRADA_SAIDA (
  SEQENTSAI INTEGER NOT NULL,
  CODVEI INTEGER NOT NULL,
  USUENT INTEGER NOT NULL,
  USUSAIDA INTEGER NOT NULL,
  CODMOT INTEGER NOT NULL,
  DATSAIDA DATE NULL,
  HORSAIDA TIME NULL,
  KMSAIDA INTEGER NULL,
  DATENT DATE NULL,
  HORENT TIME NULL,
  KMENT INTEGER NULL,
  DESTINO VARCHAR(100) NULL,
  CARGA INTEGER NULL,
  CODCARRETA INTEGER NULL,
  PRIMARY KEY(SEQENTSAI, CODVEI),
  INDEX ENTRADA_SAIDA_FKIndex2(CODVEI),
  INDEX ENTRADA_SAIDA_FKIndex3(CODMOT),
  INDEX ENTRADA_SAIDA_FKIndex3(USUSAIDA),
  INDEX ENTRADA_SAIDA_FKIndex4(USUENT)
);

CREATE TABLE FORNECEDOR (
  CODFOR INTEGER NOT NULL,
  CODUSU INTEGER NOT NULL,
  DESFOR VARCHAR(100) NULL,
  ENDFOR VARCHAR(100) NULL,
  NUMEND VARCHAR(10) NULL,
  BAIFOR VARCHAR(50) NULL,
  CEPFOR VARCHAR(15) NULL,
  CIDFOR VARCHAR(100) NULL,
  SIGUFS VARCHAR(2) NULL,
  SITFOR VARCHAR(10) NULL,
  TEL1 VARCHAR(15) NULL,
  TEL2 VARCHAR(15) NULL,
  EMAFOR VARCHAR(50) NULL,
  OBSFOR VARCHAR(300) NULL,
  CPF_CNPJ VARCHAR(20) NULL,
  PRIMARY KEY(CODFOR),
  INDEX FORNECEDOR_FKIndex1(CODUSU)
);

CREATE TABLE MANUT_GER (
  CODMAN INTEGER NOT NULL,
  CODVEI INTEGER NOT NULL,
  CODFOR INTEGER NOT NULL,
  CODUSU INTEGER NOT NULL,
  DESMAN VARCHAR(100) NULL,
  DATMAN DATE NULL,
  HORMAN TIME NULL,
  NUMORDEM INTEGER NULL,
  PRIMARY KEY(CODMAN, CODVEI),
  INDEX MANUT_GER_FKIndex1(CODUSU),
  INDEX MANUT_GER_FKIndex2(CODVEI),
  INDEX MANUT_GER_FKIndex3(CODFOR)
);

CREATE TABLE MANUT_SERV (
  CODMAN INTEGER NOT NULL,
  CODVEI INTEGER NOT NULL,
  SEQSER INTEGER NOT NULL,
  CODSER INTEGER NOT NULL,
  DATVCT DATE NULL,
  KMVCT INTEGER NULL,
  DATSER DATE NULL,
  KMSER INTEGER NULL,
  QTDSER FLOAT NULL,
  DESSER VARCHAR(200) NULL,
  VLRUNI FLOAT NULL,
  VLRUNIDES FLOAT NULL,
  VLRDES FLOAT NULL,
  SITSER VARCHAR(10) NULL,
  VLRTOT FLOAT NULL,
  TIPSER VARCHAR(50) NULL,
  NUMORDEM INTEGER NULL,
  PRIMARY KEY(CODMAN, CODVEI, SEQSER),
  INDEX MANUT_SERV_FKIndex1(CODMAN, CODVEI),
  INDEX MANUT_SERV_FKIndex2(CODSER)
);

CREATE TABLE MARCAS (
  CODMAR INTEGER NOT NULL,
  CODUSU INTEGER NOT NULL,
  DESMAR VARCHAR(100) NOT NULL,
  PRIMARY KEY(CODMAR),
  INDEX USUARIO_MARCAS(CODUSU)
);

CREATE TABLE MODELOS (
  CODMOD INTEGER NOT NULL,
  CODUSU INTEGER NOT NULL,
  CODMAR INTEGER NOT NULL,
  DESMOD VARCHAR(100) NOT NULL,
  PRIMARY KEY(CODMOD),
  INDEX MODELOS_FKIndex1(CODUSU),
  INDEX MODELOS_FKIndex2(CODMAR)
);

CREATE TABLE MOTORISTA (
  CODMOT INTEGER NOT NULL,
  CODUSU INTEGER NOT NULL,
  NOMMOT VARCHAR(100) NULL,
  APEMOT VARCHAR(50) NULL,
  DATNAS DATE NULL,
  RG VARCHAR(15) NULL,
  CPF VARCHAR(15) NULL,
  CNH VARCHAR(15) NULL,
  CATCNH VARCHAR(2) NULL,
  DATVENCNH DATE NULL,
  DATADMI DATE NULL,
  DATDEMI DATE NULL,
  FONE1 VARCHAR(15) NULL,
  FONE2 VARCHAR(15) NULL,
  EMAIL VARCHAR(50) NULL,
  SITMOT VARCHAR(20) NULL,
  ENDMOT VARCHAR(100) NULL,
  NUMEND VARCHAR(10) NULL,
  BAIMOT VARCHAR(50) NULL,
  CIDMOT VARCHAR(50) NULL,
  SIGUFS VARCHAR(2) NULL,
  TIPMOT VARCHAR(20) NULL,
  TIPSANG VARCHAR(5) NULL,
  FOTO VARCHAR(300) NULL,
  PRIMARY KEY(CODMOT),
  INDEX MOTORISTA_FKIndex1(CODUSU)
);

CREATE TABLE SERVICO (
  CODSER INTEGER NOT NULL,
  CODUSU INTEGER NOT NULL,
  DESSER VARCHAR(100) NULL,
  IN_PERIODICO VARCHAR(3) NULL,
  LIMITE_KM INTEGER NULL,
  LIMITE_DIAS INTEGER NULL,
  IN_REVISAO VARCHAR(3) NULL,
  SITSER VARCHAR(10) NULL,
  DATCAD DATE NULL,
  CODSERREV INTEGER NULL,
  PRIMARY KEY(CODSER),
  INDEX SERVICO_FKIndex1(CODUSU)
);

CREATE TABLE SERVICO_REVISAO (
  CODREV INTEGER NOT NULL,
  CODSER INTEGER NOT NULL,
  ORDEM_REV INTEGER NULL,
  DESREV VARCHAR(50) NULL,
  LIMITE_KM INTEGER NULL,
  LIMITE_DIAS INTEGER NULL,
  PRIMARY KEY(CODREV, CODSER),
  INDEX SERVICO_REVISAO_FKIndex1(CODSER)
);

CREATE TABLE USUARIO (
  CODUSU INTEGER NOT NULL,
  NOMUSU VARCHAR(100) NOT NULL,
  DESUSU VARCHAR(100) NULL,
  LOGUSU VARCHAR(20) NOT NULL,
  SENUSU VARCHAR(20) NOT NULL,
  DATCAD DATE NOT NULL,
  SITUSU VARCHAR(10) NULL,
  PRIMARY KEY(CODUSU)
);

CREATE TABLE USUPERMISSOES (
  CODUSU INTEGER NOT NULL,
  SEQPER INTEGER NOT NULL,
  NOMACT VARCHAR(50) NULL,
  DESACT VARCHAR(50) NULL,
  IMGINDEX INTEGER NULL,
  TAG INTEGER NULL,
  IN_LIBERADO VARCHAR(10) NULL,
  PRIMARY KEY(CODUSU, SEQPER),
  INDEX USUPERMISSOES_FKIndex1(CODUSU)
);

CREATE TABLE VEICULO (
  CODVEI INTEGER NOT NULL,
  USUALT INTEGER NOT NULL,
  CODUSU INTEGER NOT NULL,
  CODMOD INTEGER NOT NULL,
  CODMOT INTEGER NOT NULL,
  DESVEI VARCHAR(100) NULL,
  PLAVEI VARCHAR(15) NULL,
  PLAVEIUF CHAR(2) NULL,
  ANOFAB VARCHAR(30) NULL,
  DATAQUI DATE NULL,
  DATVEN DATE NULL,
  KMINI INTEGER NULL,
  KMATU INTEGER NULL,
  CATEGORIA VARCHAR(50) NULL,
  CHASSI VARCHAR(20) NULL,
  RENAVAM VARCHAR(15) NULL,
  TIPO VARCHAR(30) NULL,
  CODCAV INTEGER NULL,
  EIXOS VARCHAR(50) NULL,
  ALTURA FLOAT NULL,
  LARGURA FLOAT NULL,
  COMPRIMENTO FLOAT NULL,
  CUBICO FLOAT NULL,
  TARA FLOAT NULL,
  MAXPESO FLOAT NULL,
  CAPPESO INTEGER NULL,
  SITVEI VARCHAR(10) NULL,
  COR VARCHAR(30) NULL,
  OBSVEI VARCHAR(300) NULL,
  DATALT DATE NULL,
  PRIMARY KEY(CODVEI),
  INDEX VEICULO_FKIndex1(CODMOT),
  INDEX VEICULO_FKIndex2(CODMOD),
  INDEX VEICULO_FKIndex3(CODUSU),
  INDEX VEICULO_FKIndex4(USUALT)
);


