unit UDmFire;

interface

uses
  SysUtils, Classes, DB, IBDatabase, IBCustomDataSet, IBQuery, Windows, Forms,
  DBClient, Provider, DateUtils, Math,
  {frxClass, frxDBSet, frxADOComponents,}
  RpBase, RpSystem, RpDefine, RpRave, RpCon, RpConDS;

type
  TDmFire = class(TDataModule)
    Banco: TIBDatabase;
    ibtTransacao: TIBTransaction;
    CadMarcas: TIBDataSet;
    CadMarcasCODMAR: TIntegerField;
    CadMarcasCODUSU: TIntegerField;
    CadMarcasDESMAR: TIBStringField;
    ConsSql: TIBQuery;
    ConsMarcas: TIBQuery;
    ConsMarcasCODMAR: TIntegerField;
    ConsMarcasCODUSU: TIntegerField;
    ConsMarcasDESMAR: TIBStringField;
    ConsMarcasNOMUSU: TIBStringField;
    CadModelos: TIBDataSet;
    CadModelosCODMOD: TIntegerField;
    CadModelosCODUSU: TIntegerField;
    CadModelosCODMAR: TIntegerField;
    CadModelosDESMOD: TIBStringField;
    ConsModelos: TIBQuery;
    ConsModelosCODMOD: TIntegerField;
    ConsModelosCODUSU: TIntegerField;
    ConsModelosCODMAR: TIntegerField;
    ConsModelosDESMOD: TIBStringField;
    ConsModelosNOMUSU: TIBStringField;
    ConsModelosDESMAR: TIBStringField;
    CadMotoristas: TIBDataSet;
    CadMotoristasCODMOT: TIntegerField;
    CadMotoristasCODUSU: TIntegerField;
    CadMotoristasNOMMOT: TIBStringField;
    CadMotoristasAPEMOT: TIBStringField;
    CadMotoristasDATNAS: TDateField;
    CadMotoristasRG: TIBStringField;
    CadMotoristasCPF: TIBStringField;
    CadMotoristasCNH: TIBStringField;
    CadMotoristasCATCNH: TIBStringField;
    CadMotoristasDATVENCNH: TDateField;
    CadMotoristasDATADMI: TDateField;
    CadMotoristasDATDEMI: TDateField;
    CadMotoristasFONE1: TIBStringField;
    CadMotoristasFONE2: TIBStringField;
    CadMotoristasEMAIL: TIBStringField;
    CadMotoristasSITMOT: TIBStringField;
    CadMotoristasENDMOT: TIBStringField;
    CadMotoristasNUMEND: TIBStringField;
    CadMotoristasBAIMOT: TIBStringField;
    CadMotoristasCIDMOT: TIBStringField;
    CadMotoristasTIPMOT: TIBStringField;
    CadMotoristasTIPSANG: TIBStringField;
    CadMotoristasFOTO: TIBStringField;
    CadMotoristasSIGUFS: TIBStringField;
    ConsMotorista: TIBQuery;
    ConsMotoristaCODMOT: TIntegerField;
    ConsMotoristaCODUSU: TIntegerField;
    ConsMotoristaNOMMOT: TIBStringField;
    ConsMotoristaAPEMOT: TIBStringField;
    ConsMotoristaDATNAS: TDateField;
    ConsMotoristaRG: TIBStringField;
    ConsMotoristaCPF: TIBStringField;
    ConsMotoristaCNH: TIBStringField;
    ConsMotoristaCATCNH: TIBStringField;
    ConsMotoristaDATVENCNH: TDateField;
    ConsMotoristaDATADMI: TDateField;
    ConsMotoristaDATDEMI: TDateField;
    ConsMotoristaFONE1: TIBStringField;
    ConsMotoristaFONE2: TIBStringField;
    ConsMotoristaEMAIL: TIBStringField;
    ConsMotoristaSITMOT: TIBStringField;
    ConsMotoristaENDMOT: TIBStringField;
    ConsMotoristaNUMEND: TIBStringField;
    ConsMotoristaBAIMOT: TIBStringField;
    ConsMotoristaCIDMOT: TIBStringField;
    ConsMotoristaTIPMOT: TIBStringField;
    ConsMotoristaTIPSANG: TIBStringField;
    ConsMotoristaFOTO: TIBStringField;
    ConsMotoristaSIGUFS: TIBStringField;
    CadFornecedor: TIBDataSet;
    CadFornecedorCODFOR: TIntegerField;
    CadFornecedorCODUSU: TIntegerField;
    CadFornecedorDESFOR: TIBStringField;
    CadFornecedorENDFOR: TIBStringField;
    CadFornecedorNUMEND: TIBStringField;
    CadFornecedorBAIFOR: TIBStringField;
    CadFornecedorCEPFOR: TIBStringField;
    CadFornecedorCIDFOR: TIBStringField;
    CadFornecedorSIGUFS: TIBStringField;
    CadFornecedorSITFOR: TIBStringField;
    CadFornecedorTEL1: TIBStringField;
    CadFornecedorTEL2: TIBStringField;
    CadFornecedorEMAFOR: TIBStringField;
    CadFornecedorOBSFOR: TIBStringField;
    CadFornecedorCPF_CNPJ: TIBStringField;
    ConsFornecedor: TIBQuery;
    ConsFornecedorCODFOR: TIntegerField;
    ConsFornecedorCODUSU: TIntegerField;
    ConsFornecedorDESFOR: TIBStringField;
    ConsFornecedorENDFOR: TIBStringField;
    ConsFornecedorNUMEND: TIBStringField;
    ConsFornecedorBAIFOR: TIBStringField;
    ConsFornecedorCEPFOR: TIBStringField;
    ConsFornecedorCIDFOR: TIBStringField;
    ConsFornecedorSIGUFS: TIBStringField;
    ConsFornecedorSITFOR: TIBStringField;
    ConsFornecedorTEL1: TIBStringField;
    ConsFornecedorTEL2: TIBStringField;
    ConsFornecedorEMAFOR: TIBStringField;
    ConsFornecedorOBSFOR: TIBStringField;
    ConsFornecedorCPF_CNPJ: TIBStringField;
    ConsFornecedorNOMUSU: TIBStringField;
    CadVeiculo: TIBDataSet;
    CadVeiculoCODVEI: TIntegerField;
    CadVeiculoCODUSU: TIntegerField;
    CadVeiculoCODMOD: TIntegerField;
    CadVeiculoCODMOT: TIntegerField;
    CadVeiculoDESVEI: TIBStringField;
    CadVeiculoPLAVEI: TIBStringField;
    CadVeiculoPLAVEIUF: TIBStringField;
    CadVeiculoANOFAB: TIBStringField;
    CadVeiculoDATAQUI: TDateField;
    CadVeiculoDATVEN: TDateField;
    CadVeiculoKMINI: TIntegerField;
    CadVeiculoKMATU: TIntegerField;
    CadVeiculoCATEGORIA: TIBStringField;
    CadVeiculoCHASSI: TIBStringField;
    CadVeiculoRENAVAM: TIBStringField;
    CadVeiculoTIPO: TIBStringField;
    CadVeiculoCODCAV: TIntegerField;
    CadVeiculoEIXOS: TIBStringField;
    CadVeiculoALTURA: TFloatField;
    CadVeiculoLARGURA: TFloatField;
    CadVeiculoCOMPRIMENTO: TFloatField;
    CadVeiculoCUBICO: TFloatField;
    CadVeiculoTARA: TFloatField;
    CadVeiculoMAXPESO: TFloatField;
    CadVeiculoCAPPESO: TIntegerField;
    CadVeiculoSITVEI: TIBStringField;
    CadVeiculoCOR: TIBStringField;
    CadVeiculoOBSVEI: TIBStringField;
    CadVeiculoUSUALT: TIntegerField;
    CadVeiculoDATALT: TDateField;
    ConsCavalos: TIBQuery;
    ConsCavalosCODVEI: TIntegerField;
    ConsCavalosDESVEI: TIBStringField;
    ConsCavalosPLAVEI: TIBStringField;
    ConsCavalosvaDesPla: TStringField;
    ConsCavalosCODMOT: TIntegerField;
    ConsVeiculo: TIBQuery;
    ConsVeiculoCODVEI: TIntegerField;
    ConsVeiculoCODUSU: TIntegerField;
    ConsVeiculoCODMOD: TIntegerField;
    ConsVeiculoCODMOT: TIntegerField;
    ConsVeiculoDESVEI: TIBStringField;
    ConsVeiculoPLAVEI: TIBStringField;
    ConsVeiculoPLAVEIUF: TIBStringField;
    ConsVeiculoANOFAB: TIBStringField;
    ConsVeiculoDATAQUI: TDateField;
    ConsVeiculoDATVEN: TDateField;
    ConsVeiculoKMINI: TIntegerField;
    ConsVeiculoKMATU: TIntegerField;
    ConsVeiculoCATEGORIA: TIBStringField;
    ConsVeiculoCHASSI: TIBStringField;
    ConsVeiculoRENAVAM: TIBStringField;
    ConsVeiculoTIPO: TIBStringField;
    ConsVeiculoCODCAV: TIntegerField;
    ConsVeiculoEIXOS: TIBStringField;
    ConsVeiculoALTURA: TFloatField;
    ConsVeiculoLARGURA: TFloatField;
    ConsVeiculoCOMPRIMENTO: TFloatField;
    ConsVeiculoCUBICO: TFloatField;
    ConsVeiculoTARA: TFloatField;
    ConsVeiculoMAXPESO: TFloatField;
    ConsVeiculoCAPPESO: TIntegerField;
    ConsVeiculoSITVEI: TIBStringField;
    ConsVeiculoCOR: TIBStringField;
    ConsVeiculoOBSVEI: TIBStringField;
    ConsVeiculoUSUALT: TIntegerField;
    ConsVeiculoDATALT: TDateField;
    ConsVeiculoNOMMOT: TIBStringField;
    CadServico: TIBDataSet;
    CadServicoCODUSU: TIntegerField;
    CadServicoDESSER: TIBStringField;
    CadServicoIN_PERIODICO: TIBStringField;
    CadServicoLIMITE_KM: TIntegerField;
    CadServicoLIMITE_DIAS: TIntegerField;
    CadServicoIN_REVISAO: TIBStringField;
    CadServicoSITSER: TIBStringField;
    CadServicoDATCAD: TDateField;
    CadServicoCODSER: TIntegerField;
    CadServico_Revisao: TIBDataSet;
    CadServico_RevisaoCODREV: TIntegerField;
    CadServico_RevisaoCODSER: TIntegerField;
    CadServico_RevisaoORDEM_REV: TIntegerField;
    CadServico_RevisaoDESREV: TIBStringField;
    CadServico_RevisaoLIMITE_KM: TIntegerField;
    CadServico_RevisaoLIMITE_DIAS: TIntegerField;
    ConsServico: TIBQuery;
    ConsServicoCODSER: TIntegerField;
    ConsServicoCODUSU: TIntegerField;
    ConsServicoDESSER: TIBStringField;
    ConsServicoIN_PERIODICO: TIBStringField;
    ConsServicoLIMITE_KM: TIntegerField;
    ConsServicoLIMITE_DIAS: TIntegerField;
    ConsServicoIN_REVISAO: TIBStringField;
    ConsServicoSITSER: TIBStringField;
    ConsServicoDATCAD: TDateField;
    CadManut_Ger: TIBDataSet;
    CadManut_Serv: TIBDataSet;
    CadManut_GerCODMAN: TIntegerField;
    CadManut_GerCODVEI: TIntegerField;
    CadManut_GerCODUSU: TIntegerField;
    CadManut_GerCODFOR: TIntegerField;
    CadManut_GerDESMAN: TIBStringField;
    CadManut_GerDATMAN: TDateField;
    CadManut_GerHORMAN: TTimeField;
    CadManut_GerVLTDES: TFloatField;
    CadManut_ServCODMAN: TIntegerField;
    CadManut_ServCODVEI: TIntegerField;
    CadManut_ServSEQSER: TIntegerField;
    CadManut_ServCODSER: TIntegerField;
    CadManut_ServDESSER: TIBStringField;
    CadManut_ServDATVCT: TDateField;
    CadManut_ServKMVCT: TIntegerField;
    CadManut_ServDATSER: TDateField;
    CadManut_ServKMSER: TIntegerField;
    CadManut_ServQTDSER: TFloatField;
    CadManut_ServVLRUNI: TFloatField;
    CadManut_ServVLRUNIDES: TFloatField;
    CadManut_ServVLRDES: TFloatField;
    CadManut_ServSITSER: TIBStringField;
    CadManut_ServVLRTOT: TFloatField;
    CadManut_ServTIPSER: TIBStringField;
    ConsServicoLancaManut: TIBQuery;
    ConsServicoLancaManutCODSER: TIntegerField;
    ConsServicoLancaManutCODUSU: TIntegerField;
    ConsServicoLancaManutDESSER: TIBStringField;
    ConsServicoLancaManutIN_PERIODICO: TIBStringField;
    ConsServicoLancaManutLIMITE_KM: TIntegerField;
    ConsServicoLancaManutLIMITE_DIAS: TIntegerField;
    ConsServicoLancaManutIN_REVISAO: TIBStringField;
    ConsServicoLancaManutSITSER: TIBStringField;
    ConsServicoLancaManutDATCAD: TDateField;
    ClientManutencao_Serv: TClientDataSet;
    ClientManutencao_ServCODMAN: TIntegerField;
    ClientManutencao_ServCODVEI: TIntegerField;
    ClientManutencao_ServSEQSER: TIntegerField;
    ClientManutencao_ServCODSER: TIntegerField;
    ClientManutencao_ServNOMSER: TStringField;
    ClientManutencao_ServDESSER: TStringField;
    ClientManutencao_ServDATVCT: TDateField;
    ClientManutencao_ServKMVCT: TIntegerField;
    ClientManutencao_ServDATSER: TDateField;
    ClientManutencao_ServKMSER: TIntegerField;
    ClientManutencao_ServQTDSER: TIntegerField;
    ClientManutencao_ServVLRUNI: TFloatField;
    ClientManutencao_ServVLRUNIDES: TFloatField;
    ClientManutencao_ServVLRDES: TFloatField;
    ClientManutencao_ServTIPSER: TStringField;
    ClientManutencao_ServVLR_TOTAL: TAggregateField;
    ClientManutencao_ServTOTAL_DESC: TAggregateField;
    ClientManutencao_ServVLR_TOTAL_DESC: TAggregateField;
    CadServicoCODSERREV: TIntegerField;
    ConsServico_Revisao: TIBQuery;
    ConsServico_RevisaoCODREV: TIntegerField;
    ConsServico_RevisaoCODSER: TIntegerField;
    ConsServico_RevisaoORDEM_REV: TIntegerField;
    ConsServico_RevisaoDESREV: TIBStringField;
    ConsServico_RevisaoLIMITE_KM: TIntegerField;
    ConsServico_RevisaoLIMITE_DIAS: TIntegerField;
    Serv_Rev: TIBQuery;
    Serv_RevCODSER: TIntegerField;
    Serv_RevCODUSU: TIntegerField;
    Serv_RevDESSER: TIBStringField;
    Serv_RevIN_PERIODICO: TIBStringField;
    Serv_RevLIMITE_KM: TIntegerField;
    Serv_RevLIMITE_DIAS: TIntegerField;
    Serv_RevIN_REVISAO: TIBStringField;
    Serv_RevSITSER: TIBStringField;
    Serv_RevDATCAD: TDateField;
    Serv_RevCODSERREV: TIntegerField;
    ConsServicoLancaManutCODSERREV: TIntegerField;
    SqlInsertServico: TIBQuery;
    CadManut_GerNUMORDEM: TIntegerField;
    CadManut_ServNUMORDEM: TIntegerField;
    RelacaoManutencoes: TIBQuery;
    RelacaoManutencoesCODMAN: TIntegerField;
    RelacaoManutencoesCODVEI: TIntegerField;
    RelacaoManutencoesSEQSER: TIntegerField;
    RelacaoManutencoesCODSER: TIntegerField;
    RelacaoManutencoesDESSER: TIBStringField;
    RelacaoManutencoesDATVCT: TDateField;
    RelacaoManutencoesKMVCT: TIntegerField;
    RelacaoManutencoesDATSER: TDateField;
    RelacaoManutencoesKMSER: TIntegerField;
    RelacaoManutencoesQTDSER: TFloatField;
    RelacaoManutencoesVLRUNI: TFloatField;
    RelacaoManutencoesVLRUNIDES: TFloatField;
    RelacaoManutencoesVLRDES: TFloatField;
    RelacaoManutencoesSITSER: TIBStringField;
    RelacaoManutencoesVLRTOT: TFloatField;
    RelacaoManutencoesTIPSER: TIBStringField;
    RelacaoManutencoesNUMORDEM: TIntegerField;
    RelacaoManutencoesCODMAN1: TIntegerField;
    RelacaoManutencoesCODVEI1: TIntegerField;
    RelacaoManutencoesCODUSU: TIntegerField;
    RelacaoManutencoesCODFOR: TIntegerField;
    RelacaoManutencoesDESMAN: TIBStringField;
    RelacaoManutencoesDATMAN: TDateField;
    RelacaoManutencoesHORMAN: TTimeField;
    RelacaoManutencoesVLTDES: TFloatField;
    RelacaoManutencoesNUMORDEM1: TIntegerField;
    RelacaoManutencoesPLAVEI: TIBStringField;
    RelacaoManutencoesDESVEI: TIBStringField;
    RelacaoManutencoesKMATU: TIntegerField;
    RelacaoManutencoesTIPO: TIBStringField;
    RelacaoManutencoesNOMUSU: TIBStringField;
    RelacaoManutencoesCODFOR1: TIntegerField;
    RelacaoManutencoesCODUSU1: TIntegerField;
    RelacaoManutencoesDESFOR: TIBStringField;
    RelacaoManutencoesENDFOR: TIBStringField;
    RelacaoManutencoesNUMEND: TIBStringField;
    RelacaoManutencoesBAIFOR: TIBStringField;
    RelacaoManutencoesCEPFOR: TIBStringField;
    RelacaoManutencoesCIDFOR: TIBStringField;
    RelacaoManutencoesSIGUFS: TIBStringField;
    RelacaoManutencoesSITFOR: TIBStringField;
    RelacaoManutencoesTEL1: TIBStringField;
    RelacaoManutencoesTEL2: TIBStringField;
    RelacaoManutencoesEMAFOR: TIBStringField;
    RelacaoManutencoesOBSFOR: TIBStringField;
    RelacaoManutencoesCPF_CNPJ: TIBStringField;
    RelacaoManutencoesCODSER1: TIntegerField;
    RelacaoManutencoesCODUSU2: TIntegerField;
    RelacaoManutencoesDESSER1: TIBStringField;
    RelacaoManutencoesIN_PERIODICO: TIBStringField;
    RelacaoManutencoesLIMITE_KM: TIntegerField;
    RelacaoManutencoesLIMITE_DIAS: TIntegerField;
    RelacaoManutencoesIN_REVISAO: TIBStringField;
    RelacaoManutencoesSITSER1: TIBStringField;
    RelacaoManutencoesDATCAD: TDateField;
    RelacaoManutencoesCODSERREV: TIntegerField;
    ClientRelacaoManutencoes: TClientDataSet;
    ProviderRelacaoManutencoes: TDataSetProvider;
    ClientRelacaoManutencoesCODMAN: TIntegerField;
    ClientRelacaoManutencoesCODVEI: TIntegerField;
    ClientRelacaoManutencoesSEQSER: TIntegerField;
    ClientRelacaoManutencoesCODSER: TIntegerField;
    ClientRelacaoManutencoesDESSER: TWideStringField;
    ClientRelacaoManutencoesDATVCT: TDateField;
    ClientRelacaoManutencoesKMVCT: TIntegerField;
    ClientRelacaoManutencoesDATSER: TDateField;
    ClientRelacaoManutencoesKMSER: TIntegerField;
    ClientRelacaoManutencoesQTDSER: TFloatField;
    ClientRelacaoManutencoesVLRUNI: TFloatField;
    ClientRelacaoManutencoesVLRUNIDES: TFloatField;
    ClientRelacaoManutencoesVLRDES: TFloatField;
    ClientRelacaoManutencoesSITSER: TWideStringField;
    ClientRelacaoManutencoesVLRTOT: TFloatField;
    ClientRelacaoManutencoesTIPSER: TWideStringField;
    ClientRelacaoManutencoesNUMORDEM: TIntegerField;
    ClientRelacaoManutencoesCODMAN1: TIntegerField;
    ClientRelacaoManutencoesCODVEI1: TIntegerField;
    ClientRelacaoManutencoesCODUSU: TIntegerField;
    ClientRelacaoManutencoesCODFOR: TIntegerField;
    ClientRelacaoManutencoesDESMAN: TWideStringField;
    ClientRelacaoManutencoesDATMAN: TDateField;
    ClientRelacaoManutencoesHORMAN: TTimeField;
    ClientRelacaoManutencoesVLTDES: TFloatField;
    ClientRelacaoManutencoesNUMORDEM1: TIntegerField;
    ClientRelacaoManutencoesPLAVEI: TWideStringField;
    ClientRelacaoManutencoesDESVEI: TWideStringField;
    ClientRelacaoManutencoesKMATU: TIntegerField;
    ClientRelacaoManutencoesTIPO: TWideStringField;
    ClientRelacaoManutencoesNOMUSU: TWideStringField;
    ClientRelacaoManutencoesCODFOR1: TIntegerField;
    ClientRelacaoManutencoesCODUSU1: TIntegerField;
    ClientRelacaoManutencoesDESFOR: TWideStringField;
    ClientRelacaoManutencoesENDFOR: TWideStringField;
    ClientRelacaoManutencoesNUMEND: TWideStringField;
    ClientRelacaoManutencoesBAIFOR: TWideStringField;
    ClientRelacaoManutencoesCEPFOR: TWideStringField;
    ClientRelacaoManutencoesCIDFOR: TWideStringField;
    ClientRelacaoManutencoesSIGUFS: TWideStringField;
    ClientRelacaoManutencoesSITFOR: TWideStringField;
    ClientRelacaoManutencoesTEL1: TWideStringField;
    ClientRelacaoManutencoesTEL2: TWideStringField;
    ClientRelacaoManutencoesEMAFOR: TWideStringField;
    ClientRelacaoManutencoesOBSFOR: TWideStringField;
    ClientRelacaoManutencoesCPF_CNPJ: TWideStringField;
    ClientRelacaoManutencoesCODSER1: TIntegerField;
    ClientRelacaoManutencoesCODUSU2: TIntegerField;
    ClientRelacaoManutencoesDESSER1: TWideStringField;
    ClientRelacaoManutencoesIN_PERIODICO: TWideStringField;
    ClientRelacaoManutencoesLIMITE_KM: TIntegerField;
    ClientRelacaoManutencoesLIMITE_DIAS: TIntegerField;
    ClientRelacaoManutencoesIN_REVISAO: TWideStringField;
    ClientRelacaoManutencoesSITSER1: TWideStringField;
    ClientRelacaoManutencoesDATCAD: TDateField;
    ClientRelacaoManutencoesCODSERREV: TIntegerField;
    ClientRelacaoManutencoesTOTAL_GERAL: TAggregateField;
    ClientRelacaoManutencoesTOTAL_ITEM: TFloatField;
    ClientRelacaoManutencoesTOTAL_ITEM_DESC: TFloatField;
    ClientRelacaoManutencoesTOTAL_DESC: TFloatField;
    ClientRelacaoManutencoesTOTAL_GERAL_DESC: TAggregateField;
    ClientRelacaoManutencoesTOTAL_DESC_GERAL: TAggregateField;
    ConsManut_ServAlt: TIBQuery;
    ConsManut_ServAltCODMAN: TIntegerField;
    ConsManut_ServAltCODVEI: TIntegerField;
    ConsManut_ServAltSEQSER: TIntegerField;
    ConsManut_ServAltCODSER: TIntegerField;
    ConsManut_ServAltDESSER: TIBStringField;
    ConsManut_ServAltDATVCT: TDateField;
    ConsManut_ServAltKMVCT: TIntegerField;
    ConsManut_ServAltDATSER: TDateField;
    ConsManut_ServAltKMSER: TIntegerField;
    ConsManut_ServAltQTDSER: TFloatField;
    ConsManut_ServAltVLRUNI: TFloatField;
    ConsManut_ServAltVLRUNIDES: TFloatField;
    ConsManut_ServAltVLRDES: TFloatField;
    ConsManut_ServAltSITSER: TIBStringField;
    ConsManut_ServAltVLRTOT: TFloatField;
    ConsManut_ServAltTIPSER: TIBStringField;
    ConsManut_ServAltNUMORDEM: TIntegerField;
    ConsManut_ServAltCODSER1: TIntegerField;
    ConsManut_ServAltCODUSU: TIntegerField;
    ConsManut_ServAltDESSER1: TIBStringField;
    ConsManut_ServAltIN_PERIODICO: TIBStringField;
    ConsManut_ServAltLIMITE_KM: TIntegerField;
    ConsManut_ServAltLIMITE_DIAS: TIntegerField;
    ConsManut_ServAltIN_REVISAO: TIBStringField;
    ConsManut_ServAltSITSER1: TIBStringField;
    ConsManut_ServAltDATCAD: TDateField;
    ConsManut_ServAltCODSERREV: TIntegerField;
    ConsManut_GerAlt: TIBQuery;
    ClientManutencao_ServAlt: TClientDataSet;
    ClientManutencao_ServAltCODMAN: TIntegerField;
    ClientManutencao_ServAltCODVEI: TIntegerField;
    ClientManutencao_ServAltSEQSER: TIntegerField;
    ClientManutencao_ServAltCODSER: TIntegerField;
    ClientManutencao_ServAltNOMSER: TStringField;
    ClientManutencao_ServAltDESSER: TStringField;
    ClientManutencao_ServAltDATVCT: TDateField;
    ClientManutencao_ServAltKMVCT: TIntegerField;
    ClientManutencao_ServAltDATSER: TDateField;
    ClientManutencao_ServAltKMSER: TIntegerField;
    ClientManutencao_ServAltQTDSER: TIntegerField;
    ClientManutencao_ServAltVLRUNI: TFloatField;
    ClientManutencao_ServAltVLRUNIDES: TFloatField;
    ClientManutencao_ServAltVLRDES: TFloatField;
    ClientManutencao_ServAltTIPSER: TStringField;
    ClientManutencao_ServAltVLR_TOTAL: TAggregateField;
    ClientManutencao_ServAltTOTAL_DESC: TAggregateField;
    ClientManutencao_ServAltVLR_TOTAL_DESC: TAggregateField;
    ClientManutencao_ServAltLIMITE_KM: TIntegerField;
    ClientManutencao_ServAltLIMITE_DIAS: TIntegerField;
    ClientManutencao_ServAltIN_REVISAO: TStringField;
    CadVeiculoLOCALVEI: TIBStringField;
    ConsVeiculoLOCALVEI: TIBStringField;
    ConsVeiculosPatio: TIBQuery;
    ConsVeiculosPatioCODVEI: TIntegerField;
    ConsVeiculosPatioCODUSU: TIntegerField;
    ConsVeiculosPatioCODMOD: TIntegerField;
    ConsVeiculosPatioCODMOT: TIntegerField;
    ConsVeiculosPatioDESVEI: TIBStringField;
    ConsVeiculosPatioPLAVEI: TIBStringField;
    ConsVeiculosPatioPLAVEIUF: TIBStringField;
    ConsVeiculosPatioANOFAB: TIBStringField;
    ConsVeiculosPatioDATAQUI: TDateField;
    ConsVeiculosPatioDATVEN: TDateField;
    ConsVeiculosPatioKMINI: TIntegerField;
    ConsVeiculosPatioKMATU: TIntegerField;
    ConsVeiculosPatioCATEGORIA: TIBStringField;
    ConsVeiculosPatioCHASSI: TIBStringField;
    ConsVeiculosPatioRENAVAM: TIBStringField;
    ConsVeiculosPatioTIPO: TIBStringField;
    ConsVeiculosPatioCODCAV: TIntegerField;
    ConsVeiculosPatioEIXOS: TIBStringField;
    ConsVeiculosPatioALTURA: TFloatField;
    ConsVeiculosPatioLARGURA: TFloatField;
    ConsVeiculosPatioCOMPRIMENTO: TFloatField;
    ConsVeiculosPatioCUBICO: TFloatField;
    ConsVeiculosPatioTARA: TFloatField;
    ConsVeiculosPatioMAXPESO: TFloatField;
    ConsVeiculosPatioCAPPESO: TIntegerField;
    ConsVeiculosPatioSITVEI: TIBStringField;
    ConsVeiculosPatioCOR: TIBStringField;
    ConsVeiculosPatioOBSVEI: TIBStringField;
    ConsVeiculosPatioUSUALT: TIntegerField;
    ConsVeiculosPatioDATALT: TDateField;
    ConsVeiculosPatioLOCALVEI: TIBStringField;
    ConsVeiculosPatioNOMMOT: TIBStringField;
    ConsVeiculosPatioFOTO: TIBStringField;
    CadEntradaSaida: TIBDataSet;
    CadEntradaSaidaSEQENTSAI: TIntegerField;
    CadEntradaSaidaCODVEI: TIntegerField;
    CadEntradaSaidaUSUENT: TIntegerField;
    CadEntradaSaidaUSUSAIDA: TIntegerField;
    CadEntradaSaidaCODMOT: TIntegerField;
    CadEntradaSaidaDATSAIDA: TDateField;
    CadEntradaSaidaHORSAIDA: TTimeField;
    CadEntradaSaidaKMSAIDA: TIntegerField;
    CadEntradaSaidaDATENT: TDateField;
    CadEntradaSaidaHORENT: TTimeField;
    CadEntradaSaidaKMENT: TIntegerField;
    CadEntradaSaidaDESTINO: TIBStringField;
    CadEntradaSaidaCARGA: TIntegerField;
    CadEntradaSaidaCODCARRETA: TIntegerField;
    ConsVeiculosViagem: TIBQuery;
    ConsVeiculosViagemSEQENTSAI: TIntegerField;
    ConsVeiculosViagemCODVEI: TIntegerField;
    ConsVeiculosViagemUSUENT: TIntegerField;
    ConsVeiculosViagemUSUSAIDA: TIntegerField;
    ConsVeiculosViagemCODMOT: TIntegerField;
    ConsVeiculosViagemDATSAIDA: TDateField;
    ConsVeiculosViagemHORSAIDA: TTimeField;
    ConsVeiculosViagemKMSAIDA: TIntegerField;
    ConsVeiculosViagemDATENT: TDateField;
    ConsVeiculosViagemHORENT: TTimeField;
    ConsVeiculosViagemKMENT: TIntegerField;
    ConsVeiculosViagemDESTINO: TIBStringField;
    ConsVeiculosViagemCARGA: TIntegerField;
    ConsVeiculosViagemCODCARRETA: TIntegerField;
    ConsVeiculosViagemPLAVEI: TIBStringField;
    ConsVeiculosViagemDESVEI: TIBStringField;
    ConsVeiculosViagemKMATU: TIntegerField;
    ConsVeiculosViagemNOMMOT: TIBStringField;
    ConsVeiculosViagemAPEMOT: TIBStringField;
    ConsVeiculosViagemFOTO: TIBStringField;
    ConsVeiculosViagemUSUARIO_SAIDA: TIBStringField;
    ConsVeiculosViagemPLAVEI_CARRETA: TIBStringField;
    CadEntradaSaidaIN_ENGATADO: TIBStringField;
    ConsVeiculosViagemIN_ENGATADO: TIBStringField;
    CadMotoristasLOCALMOT: TIBStringField;
    ConsMotoristaLOCALMOT: TIBStringField;
    CadEntradaSaidaQTD_COMB: TFloatField;
    CadEntradaSaidaDAT_ABASTEC: TDateField;
    CadEntradaSaidaMEDIA_CONS: TFloatField;
    CadEntradaSaidaITESEL: TIBStringField;
    RelacaoEntradaSaida: TIBQuery;
    RelacaoEntradaSaidaSEQENTSAI: TIntegerField;
    RelacaoEntradaSaidaCODVEI: TIntegerField;
    RelacaoEntradaSaidaUSUENT: TIntegerField;
    RelacaoEntradaSaidaUSUSAIDA: TIntegerField;
    RelacaoEntradaSaidaCODMOT: TIntegerField;
    RelacaoEntradaSaidaDATSAIDA: TDateField;
    RelacaoEntradaSaidaHORSAIDA: TTimeField;
    RelacaoEntradaSaidaKMSAIDA: TIntegerField;
    RelacaoEntradaSaidaDATENT: TDateField;
    RelacaoEntradaSaidaHORENT: TTimeField;
    RelacaoEntradaSaidaKMENT: TIntegerField;
    RelacaoEntradaSaidaDESTINO: TIBStringField;
    RelacaoEntradaSaidaCARGA: TIntegerField;
    RelacaoEntradaSaidaCODCARRETA: TIntegerField;
    RelacaoEntradaSaidaIN_ENGATADO: TIBStringField;
    RelacaoEntradaSaidaQTD_COMB: TFloatField;
    RelacaoEntradaSaidaDAT_ABASTEC: TDateField;
    RelacaoEntradaSaidaMEDIA_CONS: TFloatField;
    RelacaoEntradaSaidaITESEL: TIBStringField;
    RelacaoEntradaSaidaPLAVEI: TIBStringField;
    RelacaoEntradaSaidaDESVEI: TIBStringField;
    RelacaoEntradaSaidaKMATU: TIntegerField;
    RelacaoEntradaSaidaNOMMOT: TIBStringField;
    RelacaoEntradaSaidaAPEMOT: TIBStringField;
    RelacaoEntradaSaidaFOTO: TIBStringField;
    RelacaoEntradaSaidaUSUARIO_SAIDA: TIBStringField;
    RelacaoEntradaSaidaUSUARIO_ENT: TIBStringField;
    RelacaoEntradaSaidaPLAVEI_CARRETA: TIBStringField;
    RelacaoManutPeriodicas: TIBQuery;
    RelacaoManutPeriodicasCODMAN: TIntegerField;
    RelacaoManutPeriodicasCODVEI: TIntegerField;
    RelacaoManutPeriodicasSEQSER: TIntegerField;
    RelacaoManutPeriodicasCODSER: TIntegerField;
    RelacaoManutPeriodicasDESSER: TIBStringField;
    RelacaoManutPeriodicasDATVCT: TDateField;
    RelacaoManutPeriodicasKMVCT: TIntegerField;
    RelacaoManutPeriodicasDATSER: TDateField;
    RelacaoManutPeriodicasKMSER: TIntegerField;
    RelacaoManutPeriodicasQTDSER: TFloatField;
    RelacaoManutPeriodicasVLRUNI: TFloatField;
    RelacaoManutPeriodicasVLRUNIDES: TFloatField;
    RelacaoManutPeriodicasVLRDES: TFloatField;
    RelacaoManutPeriodicasSITSER: TIBStringField;
    RelacaoManutPeriodicasVLRTOT: TFloatField;
    RelacaoManutPeriodicasTIPSER: TIBStringField;
    RelacaoManutPeriodicasNUMORDEM: TIntegerField;
    RelacaoManutPeriodicasCODMAN1: TIntegerField;
    RelacaoManutPeriodicasCODVEI1: TIntegerField;
    RelacaoManutPeriodicasCODUSU: TIntegerField;
    RelacaoManutPeriodicasCODFOR: TIntegerField;
    RelacaoManutPeriodicasDESMAN: TIBStringField;
    RelacaoManutPeriodicasDATMAN: TDateField;
    RelacaoManutPeriodicasHORMAN: TTimeField;
    RelacaoManutPeriodicasVLTDES: TFloatField;
    RelacaoManutPeriodicasNUMORDEM1: TIntegerField;
    RelacaoManutPeriodicasPLAVEI: TIBStringField;
    RelacaoManutPeriodicasDESVEI: TIBStringField;
    RelacaoManutPeriodicasKMATU: TIntegerField;
    RelacaoManutPeriodicasTIPO: TIBStringField;
    RelacaoManutPeriodicasNOMUSU: TIBStringField;
    RelacaoManutPeriodicasCODFOR1: TIntegerField;
    RelacaoManutPeriodicasCODUSU1: TIntegerField;
    RelacaoManutPeriodicasDESFOR: TIBStringField;
    RelacaoManutPeriodicasENDFOR: TIBStringField;
    RelacaoManutPeriodicasNUMEND: TIBStringField;
    RelacaoManutPeriodicasBAIFOR: TIBStringField;
    RelacaoManutPeriodicasCEPFOR: TIBStringField;
    RelacaoManutPeriodicasCIDFOR: TIBStringField;
    RelacaoManutPeriodicasSIGUFS: TIBStringField;
    RelacaoManutPeriodicasSITFOR: TIBStringField;
    RelacaoManutPeriodicasTEL1: TIBStringField;
    RelacaoManutPeriodicasTEL2: TIBStringField;
    RelacaoManutPeriodicasEMAFOR: TIBStringField;
    RelacaoManutPeriodicasOBSFOR: TIBStringField;
    RelacaoManutPeriodicasCPF_CNPJ: TIBStringField;
    RelacaoManutPeriodicasCODSER1: TIntegerField;
    RelacaoManutPeriodicasCODUSU2: TIntegerField;
    RelacaoManutPeriodicasDESSER1: TIBStringField;
    RelacaoManutPeriodicasIN_PERIODICO: TIBStringField;
    RelacaoManutPeriodicasLIMITE_KM: TIntegerField;
    RelacaoManutPeriodicasLIMITE_DIAS: TIntegerField;
    RelacaoManutPeriodicasIN_REVISAO: TIBStringField;
    RelacaoManutPeriodicasSITSER1: TIBStringField;
    RelacaoManutPeriodicasDATCAD: TDateField;
    RelacaoManutPeriodicasCODSERREV: TIntegerField;
    ProviderRelacaoManutPeriodicas: TDataSetProvider;
    ClientRelacaoManutPeriodicas: TClientDataSet;
    ClientRelacaoManutPeriodicasCODMAN: TIntegerField;
    ClientRelacaoManutPeriodicasCODVEI: TIntegerField;
    ClientRelacaoManutPeriodicasSEQSER: TIntegerField;
    ClientRelacaoManutPeriodicasCODSER: TIntegerField;
    ClientRelacaoManutPeriodicasDESSER: TWideStringField;
    ClientRelacaoManutPeriodicasDATVCT: TDateField;
    ClientRelacaoManutPeriodicasKMVCT: TIntegerField;
    ClientRelacaoManutPeriodicasDATSER: TDateField;
    ClientRelacaoManutPeriodicasKMSER: TIntegerField;
    ClientRelacaoManutPeriodicasQTDSER: TFloatField;
    ClientRelacaoManutPeriodicasVLRUNI: TFloatField;
    ClientRelacaoManutPeriodicasVLRUNIDES: TFloatField;
    ClientRelacaoManutPeriodicasVLRDES: TFloatField;
    ClientRelacaoManutPeriodicasSITSER: TWideStringField;
    ClientRelacaoManutPeriodicasVLRTOT: TFloatField;
    ClientRelacaoManutPeriodicasTIPSER: TWideStringField;
    ClientRelacaoManutPeriodicasNUMORDEM: TIntegerField;
    ClientRelacaoManutPeriodicasCODMAN1: TIntegerField;
    ClientRelacaoManutPeriodicasCODVEI1: TIntegerField;
    ClientRelacaoManutPeriodicasCODUSU: TIntegerField;
    ClientRelacaoManutPeriodicasCODFOR: TIntegerField;
    ClientRelacaoManutPeriodicasDESMAN: TWideStringField;
    ClientRelacaoManutPeriodicasDATMAN: TDateField;
    ClientRelacaoManutPeriodicasHORMAN: TTimeField;
    ClientRelacaoManutPeriodicasVLTDES: TFloatField;
    ClientRelacaoManutPeriodicasNUMORDEM1: TIntegerField;
    ClientRelacaoManutPeriodicasPLAVEI: TWideStringField;
    ClientRelacaoManutPeriodicasDESVEI: TWideStringField;
    ClientRelacaoManutPeriodicasKMATU: TIntegerField;
    ClientRelacaoManutPeriodicasTIPO: TWideStringField;
    ClientRelacaoManutPeriodicasNOMUSU: TWideStringField;
    ClientRelacaoManutPeriodicasCODFOR1: TIntegerField;
    ClientRelacaoManutPeriodicasCODUSU1: TIntegerField;
    ClientRelacaoManutPeriodicasDESFOR: TWideStringField;
    ClientRelacaoManutPeriodicasENDFOR: TWideStringField;
    ClientRelacaoManutPeriodicasNUMEND: TWideStringField;
    ClientRelacaoManutPeriodicasBAIFOR: TWideStringField;
    ClientRelacaoManutPeriodicasCEPFOR: TWideStringField;
    ClientRelacaoManutPeriodicasCIDFOR: TWideStringField;
    ClientRelacaoManutPeriodicasSIGUFS: TWideStringField;
    ClientRelacaoManutPeriodicasSITFOR: TWideStringField;
    ClientRelacaoManutPeriodicasTEL1: TWideStringField;
    ClientRelacaoManutPeriodicasTEL2: TWideStringField;
    ClientRelacaoManutPeriodicasEMAFOR: TWideStringField;
    ClientRelacaoManutPeriodicasOBSFOR: TWideStringField;
    ClientRelacaoManutPeriodicasCPF_CNPJ: TWideStringField;
    ClientRelacaoManutPeriodicasCODSER1: TIntegerField;
    ClientRelacaoManutPeriodicasCODUSU2: TIntegerField;
    ClientRelacaoManutPeriodicasDESSER1: TWideStringField;
    ClientRelacaoManutPeriodicasIN_PERIODICO: TWideStringField;
    ClientRelacaoManutPeriodicasLIMITE_KM: TIntegerField;
    ClientRelacaoManutPeriodicasLIMITE_DIAS: TIntegerField;
    ClientRelacaoManutPeriodicasIN_REVISAO: TWideStringField;
    ClientRelacaoManutPeriodicasSITSER1: TWideStringField;
    ClientRelacaoManutPeriodicasDATCAD: TDateField;
    ClientRelacaoManutPeriodicasCODSERREV: TIntegerField;
    ClientRelacaoManutPeriodicasvnKmRestante: TIntegerField;
    ClientRelacaoManutPeriodicasvnDiasRestante: TIntegerField;
    CadInfracoesCad: TIBDataSet;
    CadInfracoesCadCODINFRA: TIBStringField;
    CadInfracoesCadCODUSU: TIntegerField;
    CadInfracoesCadDESINFRA: TIBStringField;
    CadInfracoesCadQTD_PONTOS: TIntegerField;
    CadInfracoesCadRESPONSABILIDADE: TIBStringField;
    CadInfracoesCadGRAVIDADE: TIBStringField;
    CadInfracoesCadOBSINFRA: TIBStringField;
    CadInfracoesCadDATCAD: TDateField;
    ConsInfracoesCad: TIBQuery;
    ConsInfracoesCadCODINFRA: TIBStringField;
    ConsInfracoesCadCODUSU: TIntegerField;
    ConsInfracoesCadDESINFRA: TIBStringField;
    ConsInfracoesCadQTD_PONTOS: TIntegerField;
    ConsInfracoesCadRESPONSABILIDADE: TIBStringField;
    ConsInfracoesCadGRAVIDADE: TIBStringField;
    ConsInfracoesCadOBSINFRA: TIBStringField;
    ConsInfracoesCadDATCAD: TDateField;
    ConsInfracoesCadNOMUSU: TIBStringField;
    CadInfracoesMov: TIBDataSet;
    CadInfracoesMovSEQINFRA: TIntegerField;
    CadInfracoesMovAUTOINFRA: TIBStringField;
    CadInfracoesMovCODINFRA: TIBStringField;
    CadInfracoesMovCODMOT: TIntegerField;
    CadInfracoesMovCODVEI: TIntegerField;
    CadInfracoesMovDATINFRA: TDateField;
    CadInfracoesMovHORINFRA: TTimeField;
    CadInfracoesMovLOCAL_INFRA: TIBStringField;
    CadInfracoesMovCID_INFRA: TIBStringField;
    CadInfracoesMovSIGUFS: TIBStringField;
    CadInfracoesMovOBSINFRA: TIBStringField;
    CadInfracoesMovCONDUTOR_CONF: TIBStringField;
    CadInfracoesMovDATVCT_CONDUT: TDateField;
    CadInfracoesMovVLRINFRA: TFloatField;
    CadInfracoesMovVLRINFRADESC: TFloatField;
    CadInfracoesMovDATVCT: TDateField;
    CadInfracoesMovENVIO_CONF: TIBStringField;
    CadInfracoesMovDATENVIO: TDateField;
    CadInfracoesMovIN_CONDUTOR: TIBStringField;
    CadInfracoesMovCODUSU: TIntegerField;
    ConsInfracoesMov: TIBQuery;
    ConsInfracoesMovSEQINFRA: TIntegerField;
    ConsInfracoesMovAUTOINFRA: TIBStringField;
    ConsInfracoesMovCODINFRA: TIBStringField;
    ConsInfracoesMovCODMOT: TIntegerField;
    ConsInfracoesMovCODVEI: TIntegerField;
    ConsInfracoesMovDATINFRA: TDateField;
    ConsInfracoesMovHORINFRA: TTimeField;
    ConsInfracoesMovLOCAL_INFRA: TIBStringField;
    ConsInfracoesMovCID_INFRA: TIBStringField;
    ConsInfracoesMovSIGUFS: TIBStringField;
    ConsInfracoesMovOBSINFRA: TIBStringField;
    ConsInfracoesMovCONDUTOR_CONF: TIBStringField;
    ConsInfracoesMovDATVCT_CONDUT: TDateField;
    ConsInfracoesMovVLRINFRA: TFloatField;
    ConsInfracoesMovVLRINFRADESC: TFloatField;
    ConsInfracoesMovDATVCT: TDateField;
    ConsInfracoesMovENVIO_CONF: TIBStringField;
    ConsInfracoesMovDATENVIO: TDateField;
    ConsInfracoesMovIN_CONDUTOR: TIBStringField;
    ConsInfracoesMovCODUSU: TIntegerField;
    ConsInfracoesMovCODINFRA1: TIBStringField;
    ConsInfracoesMovCODUSU1: TIntegerField;
    ConsInfracoesMovDESINFRA: TIBStringField;
    ConsInfracoesMovQTD_PONTOS: TIntegerField;
    ConsInfracoesMovRESPONSABILIDADE: TIBStringField;
    ConsInfracoesMovGRAVIDADE: TIBStringField;
    ConsInfracoesMovOBSINFRA1: TIBStringField;
    ConsInfracoesMovDATCAD: TDateField;
    ConsInfracoesMovNOMMOT: TIBStringField;
    ConsInfracoesMovFOTO: TIBStringField;
    ConsInfracoesMovLOCALMOT: TIBStringField;
    ConsInfracoesMovDESVEI: TIBStringField;
    ConsInfracoesMovPLAVEI: TIBStringField;
    ConsInfracoesMovKMATU: TIntegerField;
    ConsInfracoesMovLOCALVEI: TIBStringField;
    ConsInfracoesMovNOMUSU: TIBStringField;
    ClientConsInfracoesMov: TClientDataSet;
    ProviderConsInfracoesMov: TDataSetProvider;
    ClientConsInfracoesMovSEQINFRA: TIntegerField;
    ClientConsInfracoesMovAUTOINFRA: TWideStringField;
    ClientConsInfracoesMovCODINFRA: TWideStringField;
    ClientConsInfracoesMovCODMOT: TIntegerField;
    ClientConsInfracoesMovCODVEI: TIntegerField;
    ClientConsInfracoesMovDATINFRA: TDateField;
    ClientConsInfracoesMovHORINFRA: TTimeField;
    ClientConsInfracoesMovLOCAL_INFRA: TWideStringField;
    ClientConsInfracoesMovCID_INFRA: TWideStringField;
    ClientConsInfracoesMovSIGUFS: TWideStringField;
    ClientConsInfracoesMovOBSINFRA: TWideStringField;
    ClientConsInfracoesMovCONDUTOR_CONF: TWideStringField;
    ClientConsInfracoesMovDATVCT_CONDUT: TDateField;
    ClientConsInfracoesMovVLRINFRA: TFloatField;
    ClientConsInfracoesMovVLRINFRADESC: TFloatField;
    ClientConsInfracoesMovDATVCT: TDateField;
    ClientConsInfracoesMovENVIO_CONF: TWideStringField;
    ClientConsInfracoesMovDATENVIO: TDateField;
    ClientConsInfracoesMovIN_CONDUTOR: TWideStringField;
    ClientConsInfracoesMovCODUSU: TIntegerField;
    ClientConsInfracoesMovCODINFRA1: TWideStringField;
    ClientConsInfracoesMovCODUSU1: TIntegerField;
    ClientConsInfracoesMovDESINFRA: TWideStringField;
    ClientConsInfracoesMovQTD_PONTOS: TIntegerField;
    ClientConsInfracoesMovRESPONSABILIDADE: TWideStringField;
    ClientConsInfracoesMovGRAVIDADE: TWideStringField;
    ClientConsInfracoesMovOBSINFRA1: TWideStringField;
    ClientConsInfracoesMovDATCAD: TDateField;
    ClientConsInfracoesMovNOMMOT: TWideStringField;
    ClientConsInfracoesMovFOTO: TWideStringField;
    ClientConsInfracoesMovLOCALMOT: TWideStringField;
    ClientConsInfracoesMovDESVEI: TWideStringField;
    ClientConsInfracoesMovPLAVEI: TWideStringField;
    ClientConsInfracoesMovKMATU: TIntegerField;
    ClientConsInfracoesMovLOCALVEI: TWideStringField;
    ClientConsInfracoesMovNOMUSU: TWideStringField;
    ClientConsInfracoesMovvnQtdPontos: TAggregateField;
    ClientConsInfracoesMovvnQtdInfra: TAggregateField;
    ClientConsInfracoesMovvnVlrTotal: TAggregateField;
    ClientConsInfracoesMovvnQtdDiasIdentCondut: TIntegerField;
    ConsVencimentoCNH: TIBQuery;
    ConsVencimentoCNHCODMOT: TIntegerField;
    ConsVencimentoCNHCODUSU: TIntegerField;
    ConsVencimentoCNHNOMMOT: TIBStringField;
    ConsVencimentoCNHAPEMOT: TIBStringField;
    ConsVencimentoCNHDATNAS: TDateField;
    ConsVencimentoCNHRG: TIBStringField;
    ConsVencimentoCNHCPF: TIBStringField;
    ConsVencimentoCNHCNH: TIBStringField;
    ConsVencimentoCNHCATCNH: TIBStringField;
    ConsVencimentoCNHDATVENCNH: TDateField;
    ConsVencimentoCNHDATADMI: TDateField;
    ConsVencimentoCNHDATDEMI: TDateField;
    ConsVencimentoCNHFONE1: TIBStringField;
    ConsVencimentoCNHFONE2: TIBStringField;
    ConsVencimentoCNHEMAIL: TIBStringField;
    ConsVencimentoCNHSITMOT: TIBStringField;
    ConsVencimentoCNHENDMOT: TIBStringField;
    ConsVencimentoCNHNUMEND: TIBStringField;
    ConsVencimentoCNHBAIMOT: TIBStringField;
    ConsVencimentoCNHCIDMOT: TIBStringField;
    ConsVencimentoCNHTIPMOT: TIBStringField;
    ConsVencimentoCNHTIPSANG: TIBStringField;
    ConsVencimentoCNHFOTO: TIBStringField;
    ConsVencimentoCNHSIGUFS: TIBStringField;
    ConsVencimentoCNHLOCALMOT: TIBStringField;
    ConsVencimentoCNHvnQtdDias: TIntegerField;
    RelacaoManutPeriodicasLOCALVEI: TIBStringField;
    ClientRelacaoManutPeriodicasLOCALVEI: TWideStringField;
    CadChega_Vei_Mot: TIBDataSet;
    CadChega_Vei_MotSEQCHE: TIntegerField;
    CadChega_Vei_MotCODUSU: TIntegerField;
    CadChega_Vei_MotCODMOT: TIntegerField;
    CadChega_Vei_MotCODVEI: TIntegerField;
    CadChega_Vei_MotDATCHE: TDateField;
    CadChega_Vei_MotHORCHE: TTimeField;
    CadChega_Vei_MotDESCRICAO: TIBStringField;
    CadChega_Vei_MotIN_VISU: TIBStringField;
    CadChega_Vei_MotDATVISU: TDateField;
    CadChega_Vei_MotHORVISU: TTimeField;
    ConsVeiculosViagemQTD_COMB: TFloatField;
    ConsVeiculosViagemDAT_ABASTEC: TDateField;
    ConsVeiculosViagemMEDIA_CONS: TFloatField;
    ConsVeiculosViagemITESEL: TIBStringField;
    ConsVeiculosViagemTIPO: TIBStringField;
    CadUsuario: TIBDataSet;
    CadUsuarioCODUSU: TIntegerField;
    CadUsuarioNOMUSU: TIBStringField;
    CadUsuarioDESUSU: TIBStringField;
    CadUsuarioLOGUSU: TIBStringField;
    CadUsuarioSENUSU: TIBStringField;
    CadUsuarioDATCAD: TDateField;
    CadUsuarioSITUSU: TIBStringField;
    ConsUsuario: TIBQuery;
    ConsUsuarioCODUSU: TIntegerField;
    ConsUsuarioNOMUSU: TIBStringField;
    ConsUsuarioDESUSU: TIBStringField;
    ConsUsuarioLOGUSU: TIBStringField;
    ConsUsuarioSENUSU: TIBStringField;
    ConsUsuarioDATCAD: TDateField;
    ConsUsuarioSITUSU: TIBStringField;
    CadUsuPermissoes: TIBDataSet;
    CadUsuPermissoesCODUSU: TIntegerField;
    CadUsuPermissoesSEQPER: TIntegerField;
    CadUsuPermissoesNOMACT: TIBStringField;
    CadUsuPermissoesDESACT: TIBStringField;
    CadUsuPermissoesIMGINDEX: TIntegerField;
    CadUsuPermissoesTAG: TIntegerField;
    CadUsuPermissoesIN_LIBERADO: TIBStringField;
    ValidaLogin: TIBQuery;
    ValidaLoginCODUSU: TIntegerField;
    ValidaLoginNOMUSU: TIBStringField;
    ValidaLoginDESUSU: TIBStringField;
    ValidaLoginLOGUSU: TIBStringField;
    ValidaLoginSENUSU: TIBStringField;
    ValidaLoginDATCAD: TDateField;
    ValidaLoginSITUSU: TIBStringField;
    CadUsuPermissoesImagemIcone: TStringField;
    CadUsuPermissoesImagemSit: TStringField;
    CadManut_ServGARANTIA: TIBStringField;
    ClientManutencao_ServGARANTIA: TStringField;
    RelacaoManutencoesGARANTIA: TIBStringField;
    ClientRelacaoManutencoesGARANTIA: TWideStringField;
    CadVeiculoIN_MONITORAR: TIBStringField;
    ConsVeiculoIN_MONITORAR: TIBStringField;
    ConsVeiculosPatioIN_MONITORAR: TIBStringField;
    ConsVeiculosViagemIN_MONITORAR: TIBStringField;
    CadChega_Vei_MotTIPMOV: TIBStringField;
    ConsLogMonitoramento: TIBQuery;
    ConsLogMonitoramentoSEQCHE: TIntegerField;
    ConsLogMonitoramentoCODUSU: TIntegerField;
    ConsLogMonitoramentoCODMOT: TIntegerField;
    ConsLogMonitoramentoCODVEI: TIntegerField;
    ConsLogMonitoramentoDATCHE: TDateField;
    ConsLogMonitoramentoHORCHE: TTimeField;
    ConsLogMonitoramentoDESCRICAO: TIBStringField;
    ConsLogMonitoramentoIN_VISU: TIBStringField;
    ConsLogMonitoramentoDATVISU: TDateField;
    ConsLogMonitoramentoHORVISU: TTimeField;
    ConsLogMonitoramentoTIPMOV: TIBStringField;
    ConsLogMonitoramentoNOMUSU: TIBStringField;
    ConsLogMonitoramentoNOMMOT: TIBStringField;
    ConsLogMonitoramentoDESVEI: TIBStringField;
    ConsLogMonitoramentoPLAVEI: TIBStringField;
    CadEntradaSaidaQTD_COMBEMP: TFloatField;
    CadEntradaSaidaQTD_COMBPOS: TFloatField;
    CadTanque_Comb: TIBDataSet;
    CadTanque_CombCODTAN: TIntegerField;
    CadTanque_CombDESTAN: TIBStringField;
    CadTanque_CombNIVEL: TFloatField;
    CadTanque_CombNIVEL_MAX: TFloatField;
    CadTanque_CombNIVEL_MIN: TFloatField;
    CadUsuarioCATUSU: TIBStringField;
    ValidaLoginCATUSU: TIBStringField;
    ConsUsuarioCATUSU: TIBStringField;
    ConsUsuarioIN_LEMBRETE: TIBStringField;
    CadUsuarioIN_LEMBRETE: TIBStringField;
    ValidaLoginIN_LEMBRETE: TIBStringField;
    CadEntradaSaidaOBS_MOTORISTA: TIBStringField;
    RelacaoEntradaSaidaQTD_COMBEMP: TFloatField;
    RelacaoEntradaSaidaQTD_COMBPOS: TFloatField;
    RelacaoEntradaSaidaOBS_MOTORISTA: TIBStringField;
    CadEntradaSaidaIN_VISUALIZADO: TIBStringField;
    RelacaoEntradaSaidaIN_VISUALIZADO: TIBStringField;
    CadConfig_Geral: TIBDataSet;
    CadConfig_GeralCODCONFIG: TIntegerField;
    CadConfig_GeralHOR_LOGOF_PORTARIA_T: TTimeField;
    CadConfig_GeralHOR_LOGOF_PORTARIA_M: TTimeField;
    CadEntradaSaidaVLR_COMBEMP: TFloatField;
    CadEntradaSaidaVLR_COMBPOS: TFloatField;
    CadEntradaSaidaVLR_PEDAGIO: TFloatField;
    CadEntradaSaidaVLR_DESCARGA: TFloatField;
    CadEntradaSaidaVLR_REFEICOES: TFloatField;
    CadEntradaSaidaVLR_OUTRAS_DESP: TFloatField;
    CadEntradaSaidaQTD_CHEQUE_REC: TIntegerField;
    CadEntradaSaidaRETORNO: TIBStringField;
    CadEntradaSaidaVLR_VIAFACIL: TFloatField;
    CadEntradaSaidaVLR_COMISSAO: TFloatField;
    CadEntradaSaidaVLR_SALARIO: TFloatField;
    RelacaoEntradaSaidaVLR_COMBEMP: TFloatField;
    RelacaoEntradaSaidaVLR_COMBPOS: TFloatField;
    RelacaoEntradaSaidaVLR_PEDAGIO: TFloatField;
    RelacaoEntradaSaidaVLR_DESCARGA: TFloatField;
    RelacaoEntradaSaidaVLR_REFEICOES: TFloatField;
    RelacaoEntradaSaidaVLR_OUTRAS_DESP: TFloatField;
    RelacaoEntradaSaidaQTD_CHEQUE_REC: TIntegerField;
    RelacaoEntradaSaidaRETORNO: TIBStringField;
    RelacaoEntradaSaidaVLR_VIAFACIL: TFloatField;
    RelacaoEntradaSaidaVLR_COMISSAO: TFloatField;
    RelacaoEntradaSaidaVLR_SALARIO: TFloatField;
    CustoKm: TIBQuery;
    CustoKmPLAVEI: TIBStringField;
    CustoKmCODVEI: TIntegerField;
    CustoKmCOMB_EMP: TFloatField;
    CustoKmCOMB_POSTO: TFloatField;
    CustoKmPEDAGIO: TFloatField;
    CustoKmVIAFACIL: TFloatField;
    CustoKmDESCARGA: TFloatField;
    CustoKmREFEICOES: TFloatField;
    CustoKmOUTRAS_DESP: TFloatField;
    CustoKmCOMISSAO: TFloatField;
    CustoKmSALARIO: TFloatField;
    CustoKmTOTAL_KM: TLargeintField;
    ClientCustoKm: TClientDataSet;
    ProviderCustoKm: TDataSetProvider;
    ClientCustoKmPLAVEI: TWideStringField;
    ClientCustoKmCODVEI: TIntegerField;
    ClientCustoKmCOMB_EMP: TFloatField;
    ClientCustoKmCOMB_POSTO: TFloatField;
    ClientCustoKmPEDAGIO: TFloatField;
    ClientCustoKmVIAFACIL: TFloatField;
    ClientCustoKmDESCARGA: TFloatField;
    ClientCustoKmREFEICOES: TFloatField;
    ClientCustoKmOUTRAS_DESP: TFloatField;
    ClientCustoKmCOMISSAO: TFloatField;
    ClientCustoKmSALARIO: TFloatField;
    ClientCustoKmTOTAL_KM: TLargeintField;
    ClientCustoKmvnPedagio: TFloatField;
    ClientCustoKmvnCombustivel: TFloatField;
    CustoKmMANUTENCOES: TIBBCDField;
    CustoKmCAMPO2: TIBBCDField;
    ClientCustoKmMANUTENCOES: TBCDField;
    ClientCustoKmCAMPO2: TBCDField;
    ClientCustoKmvnTotalGasto: TFloatField;
    ClientCustoKmvnCustoKm: TFloatField;
    ClientCustoKmvnTPedagio: TAggregateField;
    ClientCustoKmvnTCombustivel: TAggregateField;
    ClientCustoKmvnTDescarga: TAggregateField;
    ClientCustoKmvnTRefeicoes: TAggregateField;
    ClientCustoKmvnTOutrasDesp: TAggregateField;
    ClientCustoKmvnTComissao: TAggregateField;
    ClientCustoKmvnTSalario: TAggregateField;
    ClientCustoKmvnTManutencoes: TAggregateField;
    ClientCustoKmvnTGeral: TAggregateField;
    ClientCustoKmvnTotalKm: TIntegerField;
    ClientCustoKmvnTKm: TAggregateField;
    TotalManutencoes: TIBQuery;
    TotalManutencoesTOTAL: TFloatField;
    CustoKmTIPO: TIBStringField;
    ClientCustoKmTIPO: TWideStringField;
    RelacaoComissoes: TIBQuery;
    RelacaoComissoesCODMOT: TIntegerField;
    RelacaoComissoesNOMMOT: TIBStringField;
    RelacaoComissoesQTDCHEQUES: TLargeintField;
    RelacaoComissoesVALORCHEQUES: TIBBCDField;
    RelacaoComissoesTOTAL_KM: TLargeintField;
    RelacaoComissoesVALORKM: TIBBCDField;
    RelacaoComissoesTOTALCARGA: TIBBCDField;
    RelacaoComissoesVALORCARGA: TIBBCDField;
    ProviderRelacaoComissoes: TDataSetProvider;
    ClientRelacaoComissoes: TClientDataSet;
    ClientRelacaoComissoesCODMOT: TIntegerField;
    ClientRelacaoComissoesNOMMOT: TWideStringField;
    ClientRelacaoComissoesQTDCHEQUES: TLargeintField;
    ClientRelacaoComissoesVALORCHEQUES: TBCDField;
    ClientRelacaoComissoesTOTAL_KM: TLargeintField;
    ClientRelacaoComissoesVALORKM: TBCDField;
    ClientRelacaoComissoesTOTALCARGA: TBCDField;
    ClientRelacaoComissoesVALORCARGA: TBCDField;
    CargasMotorista: TIBQuery;
    CargasMotoristaCARGA: TIntegerField;
    ClientRelacaoComissoesvnTotalComissoes: TFloatField;
    ClientRelacaoComissoesvnTotalCheques: TAggregateField;
    ClientRelacaoComissoesvnTotalKm: TAggregateField;
    ClientRelacaoComissoesvnTotalCarga: TAggregateField;
    ClientRelacaoComissoesvnTotalComGeral: TAggregateField;
    CadEntradaSaidaIN_COMISSAO: TIBStringField;
    ProviderRelacaoEntradaSaida: TDataSetProvider;
    ClientRelacaoEntradaSaida: TClientDataSet;
    ClientRelacaoEntradaSaidaSEQENTSAI: TIntegerField;
    ClientRelacaoEntradaSaidaCODVEI: TIntegerField;
    ClientRelacaoEntradaSaidaUSUENT: TIntegerField;
    ClientRelacaoEntradaSaidaUSUSAIDA: TIntegerField;
    ClientRelacaoEntradaSaidaCODMOT: TIntegerField;
    ClientRelacaoEntradaSaidaDATSAIDA: TDateField;
    ClientRelacaoEntradaSaidaHORSAIDA: TTimeField;
    ClientRelacaoEntradaSaidaKMSAIDA: TIntegerField;
    ClientRelacaoEntradaSaidaDATENT: TDateField;
    ClientRelacaoEntradaSaidaHORENT: TTimeField;
    ClientRelacaoEntradaSaidaKMENT: TIntegerField;
    ClientRelacaoEntradaSaidaDESTINO: TWideStringField;
    ClientRelacaoEntradaSaidaCARGA: TIntegerField;
    ClientRelacaoEntradaSaidaCODCARRETA: TIntegerField;
    ClientRelacaoEntradaSaidaIN_ENGATADO: TWideStringField;
    ClientRelacaoEntradaSaidaQTD_COMB: TFloatField;
    ClientRelacaoEntradaSaidaDAT_ABASTEC: TDateField;
    ClientRelacaoEntradaSaidaMEDIA_CONS: TFloatField;
    ClientRelacaoEntradaSaidaITESEL: TWideStringField;
    ClientRelacaoEntradaSaidaPLAVEI: TWideStringField;
    ClientRelacaoEntradaSaidaDESVEI: TWideStringField;
    ClientRelacaoEntradaSaidaKMATU: TIntegerField;
    ClientRelacaoEntradaSaidaNOMMOT: TWideStringField;
    ClientRelacaoEntradaSaidaAPEMOT: TWideStringField;
    ClientRelacaoEntradaSaidaFOTO: TWideStringField;
    ClientRelacaoEntradaSaidaUSUARIO_SAIDA: TWideStringField;
    ClientRelacaoEntradaSaidaUSUARIO_ENT: TWideStringField;
    ClientRelacaoEntradaSaidaPLAVEI_CARRETA: TWideStringField;
    ClientRelacaoEntradaSaidavnTotalRodado: TIntegerField;
    ClientRelacaoEntradaSaidavnTotalRodadoGeral: TAggregateField;
    RelacaoEntradaSaidaIN_COMISSAO: TIBStringField;
    ClientRelacaoEntradaSaidaQTD_COMBEMP: TFloatField;
    ClientRelacaoEntradaSaidaQTD_COMBPOS: TFloatField;
    ClientRelacaoEntradaSaidaOBS_MOTORISTA: TWideStringField;
    ClientRelacaoEntradaSaidaIN_VISUALIZADO: TWideStringField;
    ClientRelacaoEntradaSaidaVLR_COMBEMP: TFloatField;
    ClientRelacaoEntradaSaidaVLR_COMBPOS: TFloatField;
    ClientRelacaoEntradaSaidaVLR_PEDAGIO: TFloatField;
    ClientRelacaoEntradaSaidaVLR_DESCARGA: TFloatField;
    ClientRelacaoEntradaSaidaVLR_REFEICOES: TFloatField;
    ClientRelacaoEntradaSaidaVLR_OUTRAS_DESP: TFloatField;
    ClientRelacaoEntradaSaidaQTD_CHEQUE_REC: TIntegerField;
    ClientRelacaoEntradaSaidaRETORNO: TWideStringField;
    ClientRelacaoEntradaSaidaVLR_VIAFACIL: TFloatField;
    ClientRelacaoEntradaSaidaVLR_COMISSAO: TFloatField;
    ClientRelacaoEntradaSaidaVLR_SALARIO: TFloatField;
    ClientRelacaoEntradaSaidaIN_COMISSAO: TWideStringField;
    ClientRelacaoComissoesImg: TStringField;
    ClientRelacaoEntradaSaidaImg: TStringField;
    ConfigComissoes: TIBQuery;
    ConfigComissoesCODCONFIG: TIntegerField;
    ConfigComissoesDATINI: TDateField;
    ConfigComissoesDATFIM: TDateField;
    ConfigComissoesVLRKM: TFloatField;
    ConfigComissoesVLRCHEQUE: TFloatField;
    ConfigComissoesPERCARGA: TFloatField;
    ConfigComissoesDATEXEC: TDateField;
    CadConfigComissoes: TIBDataSet;
    CadConfigComissoesCODCONFIG: TIntegerField;
    CadConfigComissoesDATINI: TDateField;
    CadConfigComissoesDATFIM: TDateField;
    CadConfigComissoesVLRKM: TFloatField;
    CadConfigComissoesVLRCHEQUE: TFloatField;
    CadConfigComissoesPERCARGA: TFloatField;
    CadConfigComissoesDATEXEC: TDateField;
    RvRelacaoComissoes: TRvProject;
    RvSystem: TRvSystem;
    RvClientRelacaoComissoes: TRvDataSetConnection;
    CadMotoristasVLRCOMFIXA: TFloatField;
    RelacaoComissoesVLRCOMFIXA: TFloatField;
    ClientRelacaoComissoesVLRCOMFIXA: TFloatField;
    CadManut_GerNUMDOC: TIBStringField;
    CadManut_ServNUMDOC: TIBStringField;
    CadEntradaSaidaVLR_DEPRECIASSAO: TFloatField;
    CadEntradaSaidaVLR_FINANCIAMENTOS: TFloatField;
    CadEntradaSaidaVLR_PNEUS: TFloatField;
    RelacaoEntradaSaidaVLR_DEPRECIASSAO: TFloatField;
    RelacaoEntradaSaidaVLR_FINANCIAMENTOS: TFloatField;
    RelacaoEntradaSaidaVLR_PNEUS: TFloatField;
    CustoKmDEPRECIACAO: TFloatField;
    CustoKmFINANCIAMENTOS: TFloatField;
    CustoKmPNEUS: TFloatField;
    ClientCustoKmDEPRECIACAO: TFloatField;
    ClientCustoKmFINANCIAMENTOS: TFloatField;
    ClientCustoKmPNEUS: TFloatField;
    ClientCustoKmvnTDepreciacao: TAggregateField;
    ClientCustoKmvnTFinanciamentos: TAggregateField;
    ClientCustoKmvnTPneus: TAggregateField;
    RelacaoComissoesVALORMANUAL: TIBBCDField;
    ClientRelacaoComissoesVALORMANUAL: TBCDField;
    RvClientCustoKm: TRvProject;
    DsClientCustoKm: TRvDataSetConnection;
    CadCargas: TIBDataSet;
    CadCargasIDCARGA: TIntegerField;
    CadCargasDESTINO: TIBStringField;
    CadCargasCODMOT: TIntegerField;
    CadCargasDATSAI: TDateField;
    CadCargasDATCHE: TDateField;
    CadCargasVLRADT: TFloatField;
    CadCargasVLRGAS: TFloatField;
    CadCargasVLRRET: TFloatField;
    CadCargasCODVEI: TIntegerField;
    CadCargasSITCAR: TIBStringField;
    ConsCargas: TIBQuery;
    ConsCargasIDCARGA: TIntegerField;
    ConsCargasDESTINO: TIBStringField;
    ConsCargasCODMOT: TIntegerField;
    ConsCargasDATSAI: TDateField;
    ConsCargasDATCHE: TDateField;
    ConsCargasVLRADT: TFloatField;
    ConsCargasVLRGAS: TFloatField;
    ConsCargasVLRRET: TFloatField;
    ConsCargasCODVEI: TIntegerField;
    ConsCargasSITCAR: TIBStringField;
    ConsCargasNOMMOT: TIBStringField;
    ConsCargasPLAVEI: TIBStringField;
    CadCargasVLRFREIDA: TFloatField;
    CadCargasVLRFREVOL: TFloatField;
    ConsCargasVLRFREIDA: TFloatField;
    ConsCargasVLRFREVOL: TFloatField;
    ConsCargasImg: TStringField;
    CadCargasFRERETPAG: TIBStringField;
    ConsCargasFRERETPAG: TIBStringField;
    ConsComissaoVlrFrete: TIBQuery;
    ConsComissaoVlrFreteCODMOT: TIntegerField;
    ConsComissaoVlrFreteNOMMOT: TIBStringField;
    ConsComissaoVlrFreteVLRFREIDA: TFloatField;
    ConsComissaoVlrFreteVLRFREVOL: TFloatField;
    ConsComissaoVlrFreteVLRTOTAL: TFloatField;
    ConsComissaoVlrFreteQTDCARGA: TIntegerField;
    ProviderConsComissaoVlrFrete: TDataSetProvider;
    ClientConsComissaoVlrFrete: TClientDataSet;
    ClientConsComissaoVlrFreteCODMOT: TIntegerField;
    ClientConsComissaoVlrFreteNOMMOT: TWideStringField;
    ClientConsComissaoVlrFreteVLRFREIDA: TFloatField;
    ClientConsComissaoVlrFreteVLRFREVOL: TFloatField;
    ClientConsComissaoVlrFreteVLRTOTAL: TFloatField;
    ClientConsComissaoVlrFreteQTDCARGA: TIntegerField;
    ClientConsComissaoVlrFretevnVlrCom: TFloatField;
    ConsComissaoVlrFreteVLRCOMFIXA: TFloatField;
    ClientConsComissaoVlrFreteVLRCOMFIXA: TFloatField;
    ClientConsComissaoVlrFreteTVlrFreIda: TAggregateField;
    ClientConsComissaoVlrFreteTVlrFreVol: TAggregateField;
    ClientConsComissaoVlrFreteTVlrFreTot: TAggregateField;
    ClientConsComissaoVlrFreteTVlrCom: TAggregateField;
    ClientConsComissaoVlrFretevaImg: TStringField;
    RvComissaoPorFrete: TRvProject;
    RvDsClientConsComissaoVlrFrete: TRvDataSetConnection;
    ClientConsComissaoVlrFreteTQtdCar: TAggregateField;
    CadVeiculoMEDMAXVAZ: TFloatField;
    CadVeiculoMEDMAXCAR: TFloatField;
    CadVeiculoMEDMINVAZ: TFloatField;
    CadVeiculoMEDMINCAR: TFloatField;
    ClientDiasTrabalhados: TClientDataSet;
    ClientDiasTrabalhadosCodMot: TIntegerField;
    ClientDiasTrabalhadosNomMot: TStringField;
    ClientDiasTrabalhadosvnMediaDias: TFloatField;
    CadHoras_Trab: TIBDataSet;
    CadHoras_TrabSEQENTSAI: TIntegerField;
    CadHoras_TrabCODVEI: TIntegerField;
    CadHoras_TrabSEQMOV: TIntegerField;
    CadHoras_TrabDATA: TDateField;
    CadHoras_TrabQTDMIN: TFloatField;
    DataSetProvider1: TDataSetProvider;
    ds1: TClientDataSet;
    IntegerField1: TIntegerField;
    IntegerField2: TIntegerField;
    IntegerField3: TIntegerField;
    IntegerField4: TIntegerField;
    IntegerField5: TIntegerField;
    DateField1: TDateField;
    TimeField1: TTimeField;
    IntegerField6: TIntegerField;
    DateField2: TDateField;
    TimeField2: TTimeField;
    IntegerField7: TIntegerField;
    WideStringField1: TWideStringField;
    IntegerField8: TIntegerField;
    IntegerField9: TIntegerField;
    WideStringField2: TWideStringField;
    FloatField1: TFloatField;
    DateField3: TDateField;
    FloatField2: TFloatField;
    WideStringField3: TWideStringField;
    WideStringField4: TWideStringField;
    WideStringField5: TWideStringField;
    IntegerField10: TIntegerField;
    WideStringField6: TWideStringField;
    WideStringField7: TWideStringField;
    WideStringField8: TWideStringField;
    WideStringField9: TWideStringField;
    WideStringField10: TWideStringField;
    WideStringField11: TWideStringField;
    IntegerField11: TIntegerField;
    AggregateField1: TAggregateField;
    ClientDiasTrabalhadosJan: TFloatField;
    ClientDiasTrabalhadosFev: TFloatField;
    ClientDiasTrabalhadosMar: TFloatField;
    ClientDiasTrabalhadosAbr: TFloatField;
    ClientDiasTrabalhadosMai: TFloatField;
    ClientDiasTrabalhadosJun: TFloatField;
    ClientDiasTrabalhadosJul: TFloatField;
    ClientDiasTrabalhadosAgo: TFloatField;
    ClientDiasTrabalhadosSet: TFloatField;
    ClientDiasTrabalhadosOut: TFloatField;
    ClientDiasTrabalhadosNov: TFloatField;
    ClientDiasTrabalhadosDez: TFloatField;
    ClientDiasTrabalhadosAno: TFloatField;
    ClientDiasTrabalhadosvnTotalDias: TFloatField;
    procedure ConsCavalosCalcFields(DataSet: TDataSet);
    procedure ConsMotoristaAfterScroll(DataSet: TDataSet);
    procedure CadServico_RevisaoAfterInsert(DataSet: TDataSet);
    procedure CadServico_RevisaoBeforePost(DataSet: TDataSet);
    procedure ClientRelacaoManutencoesCalcFields(DataSet: TDataSet);
    procedure ClientRelacaoManutPeriodicasCalcFields(DataSet: TDataSet);
    procedure ClientConsInfracoesMovCalcFields(DataSet: TDataSet);
    procedure ConsVencimentoCNHCalcFields(DataSet: TDataSet);
    procedure ConsUsuarioAfterScroll(DataSet: TDataSet);
    procedure ClientCustoKmCalcFields(DataSet: TDataSet);
    procedure ClientRelacaoComissoesCalcFields(DataSet: TDataSet);
    procedure ClientRelacaoEntradaSaidaCalcFields(DataSet: TDataSet);
    procedure ClientConsComissaoVlrFreteCalcFields(DataSet: TDataSet);
    procedure ClientDiasTrabalhadosCalcFields(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DmFire: TDmFire;

implementation

uses UConsMotorista, UComissaoPorFrete;

{$R *.dfm}

procedure TDmFire.CadServico_RevisaoAfterInsert(DataSet: TDataSet);
begin
   DmFire.ConsSql.Close;
   DmFire.ConsSql.SQL.Clear;
   DmFire.ConsSql.SQL.Add('SELECT MAX(CODREV) AS CODREV FROM SERVICO_REVISAO WHERE CODSER = :CODSER');
   DmFire.ConsSql.ParamByName('CODSER').AsInteger := DmFire.CadServicoCODSER.AsInteger;
   DmFire.ConsSql.Open;
   if DmFire.ConsSql.IsEmpty then
      CadServico_RevisaoCODREV.AsInteger := 1
   else
      CadServico_RevisaoCODREV.AsInteger := DmFire.ConsSql.FieldByName('CODREV').AsInteger + 1;

   CadServico_RevisaoCODSER.AsInteger := DmFire.CadServicoCODSER.AsInteger;
end;

procedure TDmFire.CadServico_RevisaoBeforePost(DataSet: TDataSet);
begin
if CadServico_RevisaoORDEM_REV.AsInteger = 0 then
   begin
     Application.MessageBox('Informe a orderm da revisão','Atenção', MB_ICONWARNING+MB_OK);
     Abort;
   end;
if (CadServico_RevisaoLIMITE_KM.AsInteger = 0) and (CadServico_RevisaoLIMITE_DIAS.AsInteger = 0) then
   begin
     Application.MessageBox('Informe o Limite de Km ou o Limite de Dias','Atenção', MB_ICONWARNING+MB_OK);
     Abort;
   end;
end;

procedure TDmFire.ClientConsComissaoVlrFreteCalcFields(DataSet: TDataSet);
begin
  ClientConsComissaoVlrFretevnVlrCom.AsFloat := ClientConsComissaoVlrFreteVLRTOTAL.AsFloat * (ClientConsComissaoVlrFreteVLRCOMFIXA.AsFloat / 100);
end;

procedure TDmFire.ClientConsInfracoesMovCalcFields(DataSet: TDataSet);
begin
   ClientConsInfracoesMovvnQtdDiasIdentCondut.AsInteger := DaysBetween(ClientConsInfracoesMovDATVCT_CONDUT.AsDateTime,Date);

   if ClientConsInfracoesMovDATVCT_CONDUT.AsDateTime < date then
      ClientConsInfracoesMovvnQtdDiasIdentCondut.AsInteger := ClientConsInfracoesMovvnQtdDiasIdentCondut.AsInteger * (-1);
end;

procedure TDmFire.ClientCustoKmCalcFields(DataSet: TDataSet);
begin
  ClientCustoKmvnPedagio.Value := RoundTo(RoundTo(ClientCustoKmPEDAGIO.Value,-3) + RoundTo(ClientCustoKmVIAFACIL.Value,-3),-3);
  ClientCustoKmvnCombustivel.Value := RoundTo(RoundTo(ClientCustoKmCOMB_EMP.Value,-3) + RoundTo(ClientCustoKmCOMB_POSTO.Value,-3),-3);

  ClientCustoKmvnTotalGasto.Value := RoundTo(RoundTo(ClientCustoKmvnPedagio.Value,-3) + RoundTo(ClientCustoKmvnCombustivel.Value,-3) +
                                             RoundTo(ClientCustoKmDESCARGA.Value,-3) + RoundTo(ClientCustoKmREFEICOES.Value,-3) +
                                             RoundTo(ClientCustoKmOUTRAS_DESP.Value,-3) + RoundTo(ClientCustoKmCOMISSAO.Value,-3) +
                                             RoundTo(ClientCustoKmSALARIO.Value,-3) + RoundTo(ClientCustoKmMANUTENCOES.Value,-3),-3) +
                                             RoundTo(ClientCustoKmDEPRECIACAO.Value,-3) + RoundTo(ClientCustoKmFINANCIAMENTOS.Value,-3)+
                                             RoundTo(ClientCustoKmPNEUS.Value,-3);

 ClientCustoKmvnCustoKm.Value := RoundTo(RoundTo(ClientCustoKmvnTotalGasto.Value,-3) / ClientCustoKmTOTAL_KM.Value,-3);

 ClientCustoKmvnTotalKm.Value := ClientCustoKmTOTAL_KM.AsInteger;

end;

procedure TDmFire.ClientDiasTrabalhadosCalcFields(DataSet: TDataSet);
begin
  ClientDiasTrabalhadosvnTotalDias.AsFloat := ClientDiasTrabalhadosJan.AsFloat +
                                                ClientDiasTrabalhadosFev.AsFloat +
                                                ClientDiasTrabalhadosMar.AsFloat +
                                                ClientDiasTrabalhadosAbr.AsFloat +
                                                ClientDiasTrabalhadosMai.AsFloat +
                                                ClientDiasTrabalhadosJun.AsFloat +
                                                ClientDiasTrabalhadosJul.AsFloat +
                                                ClientDiasTrabalhadosAgo.AsFloat +
                                                ClientDiasTrabalhadosSet.AsFloat +
                                                ClientDiasTrabalhadosOut.AsFloat +
                                                ClientDiasTrabalhadosNov.AsFloat +
                                                ClientDiasTrabalhadosDez.AsFloat;

  ClientDiasTrabalhadosvnMediaDias.AsFloat := ClientDiasTrabalhadosvnTotalDias.AsFloat / 12;
end;

procedure TDmFire.ClientRelacaoComissoesCalcFields(DataSet: TDataSet);
begin
    if ClientRelacaoComissoesVLRCOMFIXA.Value = 0 then
       begin
          ClientRelacaoComissoesvnTotalComissoes.Value := ClientRelacaoComissoesVALORCHEQUES.Value +
                                                          ClientRelacaoComissoesVALORKM.Value +
                                                          ClientRelacaoComissoesVALORCARGA.Value;
       end
    else
      begin
         ClientRelacaoComissoesvnTotalComissoes.Value := ClientRelacaoComissoesVALORCHEQUES.Value + ClientRelacaoComissoesVLRCOMFIXA.AsFloat;
      end;

end;

procedure TDmFire.ClientRelacaoEntradaSaidaCalcFields(DataSet: TDataSet);
begin
   if ClientRelacaoEntradaSaidaKMENT.AsInteger > 0 then
      ClientRelacaoEntradaSaidavnTotalRodado.Value := ClientRelacaoEntradaSaidaKMENT.AsInteger - ClientRelacaoEntradaSaidaKMSAIDA.AsInteger
   else
      ClientRelacaoEntradaSaidavnTotalRodado.Value := 0;
end;

procedure TDmFire.ClientRelacaoManutencoesCalcFields(DataSet: TDataSet);
begin
  ClientRelacaoManutencoesTOTAL_ITEM.Value := ClientRelacaoManutencoesQTDSER.Value * ClientRelacaoManutencoesVLRUNI.Value;
  ClientRelacaoManutencoesTOTAL_ITEM_DESC.Value := ClientRelacaoManutencoesQTDSER.Value * ClientRelacaoManutencoesVLRUNIDES.Value;
  ClientRelacaoManutencoesTOTAL_DESC.Value := ClientRelacaoManutencoesQTDSER.Value * ClientRelacaoManutencoesVLRDES.Value;
end;

procedure TDmFire.ClientRelacaoManutPeriodicasCalcFields(DataSet: TDataSet);
begin
  if ClientRelacaoManutPeriodicasKMVCT.AsInteger > 0 then
     begin
       ClientRelacaoManutPeriodicasvnKmRestante.AsInteger := ClientRelacaoManutPeriodicasKMVCT.AsInteger - ClientRelacaoManutPeriodicasKMATU.AsInteger;
     end
  else
     begin
       ClientRelacaoManutPeriodicasvnKmRestante.AsInteger := 0;
     end;

    if ClientRelacaoManutPeriodicasDATVCT.AsDateTime <> StrToDateTime('30/12/1899') then
       begin
         ClientRelacaoManutPeriodicasvnDiasRestante.AsInteger := DaysBetween(Date,ClientRelacaoManutPeriodicasDATVCT.AsDateTime);
       end
    else
       begin
         ClientRelacaoManutPeriodicasvnDiasRestante.AsInteger := 0;
       end;

    if ClientRelacaoManutPeriodicasDATVCT.AsDateTime < Date then
       begin
         ClientRelacaoManutPeriodicasvnDiasRestante.AsInteger := ClientRelacaoManutPeriodicasvnDiasRestante.AsInteger * (-1);
       end;


end;

procedure TDmFire.ConsCavalosCalcFields(DataSet: TDataSet);
begin
  ConsCavalosvaDesPla.AsString := ConsCavalosDESVEI.AsString + '  -  '+ConsCavalosPLAVEI.AsString;
end;

procedure TDmFire.ConsMotoristaAfterScroll(DataSet: TDataSet);
begin
  FConsMotorista.ImgAlu.Picture := nil;

if trim(DmFire.ConsMotoristaFOTO.AsString) <> '' then
   begin
     FConsMotorista.btnVisualizaImg.Enabled := true;
   end
else
   begin
     FConsMotorista.btnVisualizaImg.Enabled := false;
   end;
end;

procedure TDmFire.ConsUsuarioAfterScroll(DataSet: TDataSet);
begin
   CadUsuPermissoes.Close;
   CadUsuPermissoes.ParamByName('CODUSU').Value := ConsUsuarioCODUSU.Value;
   CadUsuPermissoes.Open;
end;

procedure TDmFire.ConsVencimentoCNHCalcFields(DataSet: TDataSet);
begin
  ConsVencimentoCNHvnQtdDias.AsInteger := DaysBetween(Date,ConsVencimentoCNHDATVENCNH.AsDateTime);
  if ConsVencimentoCNHDATVENCNH.AsDateTime < Date then
     ConsVencimentoCNHvnQtdDias.AsInteger := ConsVencimentoCNHvnQtdDias.AsInteger * (-1);

end;

end.
